1. Crea un array da una lista Python

In [6]:
import numpy as np

numeri = [1, 2, 3, 4, 5]

ar = np.array(numeri)

ar



array([1, 2, 3, 4, 5])

2. Crea un array pieno di zeri

In [4]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

3. Crea un array da 0 a 9

In [8]:
b = np.array(range(10))


b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4. Crea un array 3x3 di numeri casuali

In [10]:
matrice = np.random.randint(0, 100, size=(3,3))

matrice

array([[21, 50, 62],
       [ 2, 26, 80],
       [ 0, 60, 52]])

5. Crea un array da 0 a 5 e utlizza il metodo reshape

In [11]:
arr = np.array(range(6))
matrix = arr.reshape(2,3)

matrix

array([[0, 1, 2],
       [3, 4, 5]])

6. Trova il valore massimo e minimo di un array

In [ ]:
array = np.random.randint(0,100,size=(20))

array.max()
array.min()


3

7. Somma tutti gli elementi di un array

In [25]:
array.sum()

1069

8. Calcola la Media degli elementi di un array

In [26]:
array.mean()

53.45

9. Somma due array

In [29]:
array1 = np.random.randint(0,100,size=(20))
ar_sum = array + array1
ar_sum

array([113,  93,   9,  52, 110,  44, 100,  83, 129,  74, 108,  72, 119,
       161, 171, 160, 156, 191, 180, 104])

10. Confronto elemento per elemento di due array

In [31]:
confronto = array == array1

confronto

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

11. Filtra elementi maggiori di 3 in un array

12. Inverti l’ordine di un array

13. Salva e carica un array su file

14. Moltiplicazione elemento per elemento tra array

15. Crea un array e sostituisci i valori < 50 con 0